### ISSUE TITLE
windows phone 10 打开闪退

### ISSUE THREAD

**Issue by Rustic-Z** [WEdotStudio/Fcus-UWP#12]
你好，请问这个项目作者还维护吗？windows phone 10 打开应用闪退，OS版本10.0.15063.138。

**Comment by patrick330602** [comment]
我还在维护的，但是目前在修复另外一款UWP, 可以提供一下机型吗？我可以看一下log

**Comment by patrick330602** [comment]
理论上测试版已经修复问题。暂时关闭这个issue。
